# 设置 tf 和 pytorch 的随机数种子




In [63]:
# tensorflow
import tensorflow as tf
import random
import numpy as np
random_seed = 60
tf.random.set_seed(random_seed)
# np.random.seed(random_seed)
# random.seed(random_seed)

tf_tensor= tf.random.uniform(shape= (4,),dtype= tf.float32)
print(tf_tensor)

tf.Tensor([0.48295116 0.8671261  0.11581647 0.97698903], shape=(4,), dtype=float32)


In [34]:
# pytorch
import torch
import random
import numpy as np
 
random_seed = 60
torch.manual_seed(random_seed)
np.random.seed(random_seed)
random.seed(random_seed)

torch_tensor= torch.rand(size= (4,), dtype= torch.float32)
print(torch_tensor)


tensor([0.0236, 0.3107, 0.8581, 0.4991])


In [30]:
# experiment
import torch

# 设置随机种子
torch.manual_seed(60)

# 创建一个随机数张量
random_tensor_1 = torch.rand(3, 3)
print("第一次随机数生成结果:")
print(random_tensor_1)

# 再次随机生成，第二次结果和第一次是一样的
torch.manual_seed(60)
random_tensor_2 = torch.rand(3, 3)
print("第二次随机数生成结果:")
print(random_tensor_2)

# 重新设置不的随机种子
torch.manual_seed(456)

# 再次创建一个随机数张量：因为设置了不同的随机数种子，这次生成的结果不和之前两次不同
random_tensor_3 = torch.rand(3, 3)
print("\n第三次随机数生成结果:")
print(random_tensor_3)


第一次随机数生成结果:
tensor([[0.0236, 0.3107, 0.8581],
        [0.4991, 0.7348, 0.6979],
        [0.4319, 0.7147, 0.1445]])
第二次随机数生成结果:
tensor([[0.0236, 0.3107, 0.8581],
        [0.4991, 0.7348, 0.6979],
        [0.4319, 0.7147, 0.1445]])

第三次随机数生成结果:
tensor([[0.6815, 0.0039, 0.7451],
        [0.7946, 0.6127, 0.6803],
        [0.9820, 0.0019, 0.1609]])


In [65]:
import numpy as np
import tensorflow as tf
import torch

# 设置随机种子
seed = 60
np.random.seed(seed)

# 使用 NumPy 生成随机数
np_random_numbers = np.random.rand(4)

# TensorFlow 使用相同的 NumPy 随机数
tf_random_numbers = tf.convert_to_tensor(np_random_numbers, dtype=tf.float64)

# PyTorch 使用相同的 NumPy 随机数
torch_random_numbers = torch.tensor(np_random_numbers, dtype=torch.float64)

print("NumPy Random Numbers:", np_random_numbers)
print("TensorFlow Random Numbers:", tf_random_numbers.numpy())
print("PyTorch Random Numbers:", torch_random_numbers.numpy())

NumPy Random Numbers: [0.30087333 0.18694582 0.32318268 0.66574957]
TensorFlow Random Numbers: [0.30087333 0.18694582 0.32318268 0.66574957]
PyTorch Random Numbers: [0.30087333 0.18694582 0.32318268 0.66574957]


In [64]:
import torch

tensor = torch.randn(3, )
size = tensor.size()

# 将 torch.Size 对象转换为整数列表
size_list = list(size)
print(size_list)  # 输出: [3, 4, 5]


[3]
