In [33]:
import tensorflow as tf
import numpy as np

PI = np.pi

class Rays:
    def __init__(self, xpr):
        self.xpr = xpr

class ExampleClass:
    def __init__(self):
        self._dtype = tf.complex64

    def _step_11_phase_matrix(self, phi, rays):
        # pylint: disable=line-too-long
        r"""
        Compute matrix with random phases in (7.5-22)

        Input
        -----
        phi : [batch size, num TXs, num RXs, num clusters, num rays, 4], tf.float
            Initial phases for all combinations of polarization

        rays : Rays
            Rays

        Output
        ------
        h_phase : [batch size, num TXs, num RXs, num clusters, num rays, 2, 2], tf.complex
            Matrix with random phases in (7.5-22)
        """
        xpr = rays.xpr

        xpr_scaling = tf.complex(tf.sqrt(1/xpr),
            tf.constant(0., self._dtype.real_dtype))
        e0 = tf.exp(tf.complex(tf.constant(0., self._dtype.real_dtype),
            phi[...,0]))
        e3 = tf.exp(tf.complex(tf.constant(0., self._dtype.real_dtype),
            phi[...,3]))
        e1 = xpr_scaling*tf.exp(tf.complex(tf.constant(0.,
                                self._dtype.real_dtype), phi[...,1]))
        e2 = xpr_scaling*tf.exp(tf.complex(tf.constant(0.,
                                self._dtype.real_dtype), phi[...,2]))
        shape = tf.concat([tf.shape(e0), [2,2]], axis=-1)
        h_phase = tf.reshape(tf.stack([e0, e1, e2, e3], axis=-1), shape)

        return h_phase

# 示例
phi = tf.random.uniform([2, 2, 2, 2, 2, 4], minval=-PI, maxval=PI, dtype=tf.float32)
rays = Rays(tf.random.uniform([2, 2, 2, 2, 2], minval=0.1, maxval=2.0, dtype=tf.float32))
example = ExampleClass()
h_phase = example._step_11_phase_matrix(phi, rays)
print(h_phase)


tf.Tensor(
[[[[[[[ 0.44075155+0.89762914j  0.5268761 -1.2098328j ]
      [-0.3002821 +1.2849609j  -0.66258305-0.7489885j ]]

     [[-0.97957385-0.2010848j  -0.16425951-0.7285877j ]
      [-0.01054482+0.7467998j  -0.7935714 -0.6084772j ]]]


    [[[-0.27058995-0.9626947j  -1.4689273 -2.1868231j ]
      [-1.3353224 +2.2708714j  -0.7279607 +0.6856189j ]]

     [[-0.9996121 +0.02785123j  0.23648417+0.72982717j]
      [-0.02667142-0.76672095j -0.09694957+0.99528927j]]]]



   [[[[-0.78565294+0.61866754j -0.6178215 +0.54785836j]
      [-0.81949043+0.1014278j  -0.99917054-0.0407208j ]]

     [[ 0.46989986+0.88271976j -0.14707784-0.69287103j]
      [ 0.2972565 +0.6429158j  -0.84261745-0.53851265j]]]


    [[[-0.31636527+0.9486374j   0.27918237-0.8404133j ]
      [ 0.3224778 -0.82476985j -0.01756713+0.9998457j ]]

     [[ 0.40072876+0.91619676j -0.30097038-1.6435984j ]
      [-0.14775388+1.6643821j   0.09168518-0.99578804j]]]]]




  [[[[[ 0.98852026-0.15108845j -0.6978547 +1.158741j  ]
      [

In [37]:
import torch
import numpy as np

PI = np.pi

class Rays:
    def __init__(self, xpr):
        self.xpr = xpr

class ExampleClass:
    def __init__(self):
        self._dtype = torch.complex64
        self._real_dtype = torch.float32

    def _step_11_phase_matrix(self, phi, rays):
        r"""
        Compute matrix with random phases in (7.5-22)

        Input
        -----
        phi : [batch size, num TXs, num RXs, num clusters, num rays, 4], torch.float
            Initial phases for all combinations of polarization

        rays : Rays
            Rays

        Output
        ------
        h_phase : [batch size, num TXs, num RXs, num clusters, num rays, 2, 2], torch.complex
            Matrix with random phases in (7.5-22)
        """
        xpr = rays.xpr

        xpr_scaling = torch.sqrt(1/xpr).to(self._real_dtype).to(self._dtype)
        e0 = torch.exp(1j * phi[...,0].to(self._real_dtype)).to(self._dtype)
        e3 = torch.exp(1j * phi[...,3].to(self._real_dtype)).to(self._dtype)
        e1 = xpr_scaling * torch.exp(1j * phi[...,1].to(self._real_dtype)).to(self._dtype)
        e2 = xpr_scaling * torch.exp(1j * phi[...,2].to(self._real_dtype)).to(self._dtype)
        shape = torch.cat([torch.tensor(e0.shape), torch.tensor([2,2])])
        h_phase = torch.stack([e0, e1, e2, e3], dim=-1).reshape(shape)

        return h_phase

# 示例
phi = torch.rand([2, 2, 2, 2, 2, 4]) * 2 * PI - PI
rays = Rays(torch.rand([2, 2, 2, 2, 2]) * (2.0 - 0.1) + 0.1)
example = ExampleClass()
h_phase = example._step_11_phase_matrix(phi, rays)
print(h_phase)


TypeError: reshape(): argument 'shape' (position 1) must be tuple of ints, but found element of type Tensor at pos 0

In [3]:
import tensorflow as tf

# 任意维度的索引和更新值
indices = tf.constant([[0, 0], [1, 1], [2, 2]])
updates = tf.constant([1, 2, 3])
shape = tf.constant([3, 3])

# 使用 tf.scatter_nd 更新张量
output = tf.scatter_nd(indices, updates, shape)

print(output)  # 输出:
# [[1, 0, 0],
#  [0, 2, 0],
#  [0, 0, 3]]


2024-07-30 12:16:01.281262: E external/local_xla/xla/stream_executor/cuda/cuda_dnn.cc:9261] Unable to register cuDNN factory: Attempting to register factory for plugin cuDNN when one has already been registered
2024-07-30 12:16:01.281318: E external/local_xla/xla/stream_executor/cuda/cuda_fft.cc:607] Unable to register cuFFT factory: Attempting to register factory for plugin cuFFT when one has already been registered
2024-07-30 12:16:01.296813: E external/local_xla/xla/stream_executor/cuda/cuda_blas.cc:1515] Unable to register cuBLAS factory: Attempting to register factory for plugin cuBLAS when one has already been registered
2024-07-30 12:16:01.335604: I tensorflow/core/platform/cpu_feature_guard.cc:182] This TensorFlow binary is optimized to use available CPU instructions in performance-critical operations.
To enable the following instructions: AVX2 FMA, in other operations, rebuild TensorFlow with the appropriate compiler flags.
2024-07-30 12:16:02.698205: W tensorflow/compiler/tf2

tf.Tensor(
[[1 0 0]
 [0 2 0]
 [0 0 3]], shape=(3, 3), dtype=int32)


2024-07-30 12:16:04.606045: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1929] Created device /job:localhost/replica:0/task:0/device:GPU:0 with 18425 MB memory:  -> device: 0, name: NVIDIA GeForce RTX 3080, pci bus id: 0000:86:00.0, compute capability: 8.6


In [11]:
import torch

def scatter_nd_torch(indices, updates, shape):
    # 创建一个初始张量
    output = torch.zeros(shape, dtype=updates.dtype)
    
    # 将 indices 展开为一维，计算对应的线性索引
    flat_indices = torch.zeros(indices.shape[0], dtype=torch.long)
    stride = 1
    for i in reversed(range(indices.shape[1])):
        flat_indices += indices[:, i] * stride
        stride *= shape[i]
    
    # 使用 scatter_ 方法更新平坦输出
    for i, idx in enumerate(flat_indices):
        output[idx] = updates[i]

    return output

# 定义任意维度的索引和更新值
indices = torch.tensor([[4], [3], [1], [7]])
updates = torch.tensor([9, 10, 11, 12])
shape = torch.tensor([8])

# 使用 scatter_nd 更新张量
output = scatter_nd_torch(indices, updates, shape)

print(output)
# 期望输出:
# tensor([[[[0, 0, 0, 0], [0, 0, 0, 0], [0, 0, 0, 0], [0, 0, 0, 0]],
#          [[5, 5, 5, 5], [6, 6, 6, 6], [7, 7, 7, 7], [8, 8, 8, 8]],
#          [[0, 0, 0, 0], [0, 0, 0, 0], [0, 0, 0, 0], [0, 0, 0, 0]],
#          [[5, 5, 5, 5], [6, 6, 6, 6], [7, 7, 7, 7], [8, 8, 8, 8]]]])


tensor([ 0, 11,  0, 10,  9,  0,  0, 12])
